### ISSUE TITLE
Better issue messages

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#13]
Currently, all the error messages are the same.
![image](https://user-images.githubusercontent.com/56029311/135998462-a47b10ee-3cd3-4800-9a07-869d2f123ca7.png)
We need better issue messages for various situations.
Situations:
- Can't speak on the voice channel.
- Can't send messages in the text channel.
- Can't embed messages.
- Can't reply.
- Can't mention people.
If you think of any more please comment here. Also, try to find a way to make these error messages easier to code. It would be better if we don't have to hard code each condition but if there is no smarter alternative, prefer switch-case statements over if-else as they tend to look messy.

**Comment by kailash360** [comment]
I want to work on this issue

**Comment by hitenSharm** [comment]
Yeah if there is no alternative then we will just have to hardcode it. Go ahead.

**Comment by kailash360** [comment]
@hitenSharm , I have added PR #16 for this issue.
