### ISSUE TITLE
Update Readme images

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#19]
Update Readme images with all the updated commands.

**Comment by Prakarsh-Kaushik** [comment]
I would like to contribute to this issue.
Where can I find the updated command?
and can you please assign this to me?

**Comment by hitenSharm** [comment]
It would be better if you could do a local setup and capture the images.

**Comment by Prakarsh-Kaushik** [comment]
Sorry but I'm unable to run the bot on a local terminal. I don't know how to. I can run it by adding it to my server

**Comment by hitenSharm** [comment]
That's ok, the installation steps are already in the readme. If you could tell me what exactly the issue is, I might be able to help you, otherwise just let me know if you feel you can't work on this issue.

**Comment by Prakarsh-Kaushik** [comment]
I'm very much interested in working on this but the problem I'm facing is regarding client configuration. As mentioned in README.md, I've already installed npm, nodemon, tenorjs and discord.js in the project folder. When I run the cmd, it shows this error 

![image](https://user-images.githubusercontent.com/63556277/136703304-92c5676d-d42c-4ecd-8cc7-0c8efdd349ef.png)

**Comment by kailash360** [comment]
Can I work on this issue?
