### ISSUE TITLE
Repeated code in dev branch

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#23]
Thanks to the contributions of @markvrma , the music features have become better but there still is quite a bit of repeated code.
Example
```
 try {
      msg.member.voice.channel.members;
     guildQueue.stop(); //for the stop function
   } catch (error) {
       msg.reply(
              "Only the ones who hear the music may stop the music \n -Aristotle, probably"
              );
  }
```
This is to check if the user is in the voice channel and if yes, then he/she can ask the bot to stop the music.
This kind of code is repeated multiple times. That is not ideal. There is a util folder where you will have to create a new file to check if the user is in the voice channel. Based on the output from that you need to let the bot know whether or not to stop/skip/pause/resume/play the music.

**Comment by markvrma** [comment]
I would like to work on this.
