### ISSUE TITLE
Text to emoji command

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#30]
[API for conversion](https://funtranslations.com/api/emoji)
**Purpose:** Arguments sent by the user get emojified.
_Steps:_

- Make a file in the bot functions folder(give proper name). This should do the Axios related work.
- Make a file in the commands which will do the final work.
- Command : _!obemojify "text here"_

**P.S.**
If this API doesn't work well let me know, also record a video of this working using loom when making a PR

**Comment by hitenSharm** [comment]
Hey @AmanPachori, let me know if you are making progress.

**Comment by kailash360** [comment]
@hitenSharm, if this issue is still open, I would like to work on it.

**Comment by kailash360** [comment]
@hiten, the API is returning data in form of HTML entities. so, it looks like this.
![image](https://user-images.githubusercontent.com/75155230/138244802-8f3669a1-e9f0-47b4-ab62-0bc37a84d5df.png)

I found this npm package [html-entities](https://www.npmjs.com/package/html-entities) that can convert HTML entities to unicode. Should I proceed with this library?
