### ISSUE TITLE
Music related bug

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#31]
![image](https://user-images.githubusercontent.com/56029311/137847918-3ae588f3-e92f-4d50-a8b7-b8dd43acf868.png)
Thanks to @markvrma contribution. The skip command works in a similar manner to the Rhythm bot and only skip if there are more than 50% of users asking to skip.
_**The bug:**_  
It counts the users in the VC(excluding the bot) but I don't think it excludes people who are deafened/self-deafened, which should happen.
_**The Solution:**_
You will probably have to iterate through all users to check.
Make a file in the utils folder which does the check for the number of users like that.

**Comment by markvrma** [comment]
I would like to work on this
