### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#33]
I think the installation steps are a bit difficult for some people to understand so I think they need to be updated(with new features)
Steps:
- Get the Node V16 and DiscordJS V13
- Get Discord Token
- Get Tenor API key
- Set your own Discord ID as TECNO environment variable
- Set your bot discord id as BOT environment variable
I will only assign this issue to someone who has all the commands working and has contributed to the repo, so if I have missed any steps they will be able to let me know.

**Comment by markvrma** [comment]
I would like to work on this

**Comment by markvrma** [comment]
Should I update the images too?

**Comment by hitenSharm** [comment]
Most images were updated, the dev branch doesn't have the anime command image, so put that in.
