### ISSUE TITLE
!anime command bug

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#36]
Earlier, the !anime command used the old API method. That method doesn't work anymore and now you need to get the link of the image instead and use it to do a search.
[API](https://soruly.github.io/trace.moe-api/#/)
I don't think you will need base64 encoding either anymore and you will have to use blob. [Migrating from old API](https://soruly.github.io/trace.moe-api/#/migrate)
So basically, all the methods will have to be changed. Whatever changes you make will be limited to the animeFinder.js in botFunctions and the command folder function for anime.
P.S. It should work the same way it did before

**Comment by markvrma** [comment]
I would like to work on this

**Comment by markvrma** [comment]
Can i directly add the image link to the api rather than converting to blob? since it's already hosted on discord.

![anime](https://user-images.githubusercontent.com/78155861/138403306-ca4ee218-061f-4b0a-9b50-797e61571b1a.png)

show name is in `anilist` object.

**Comment by hitenSharm** [comment]
Yeah sure. I was under the impression that it might not work, but if it works, then great!
