### ISSUE TITLE
Chatbot bug

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#39]
@markvrma , Your contribution to make the smartest chatbot does work pretty well, but if the repo is down then it should send an appropriate response.
We need to wrap the chatbot in a try-catch to avoid these scenarions.
![image](https://user-images.githubusercontent.com/56029311/138395025-67c5bf8a-46f7-4c80-a59e-3ee72d0c8b10.png)

**Comment by markvrma** [comment]
Yes, I’ll do it at the earliest 👍

**Comment by markvrma** [comment]
@hitenSharm could you please open this issue again so that i can resubmit the PR as this wasn't counted in the original PR i made? I talked to a coordinator and he said that each PR only picks the hardest label and the database cant be changed. Sorry for the inconvenience caused.
