### ISSUE TITLE
Insult Feature

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#4]
You can only tell the bot to insult 1 person currently. That is hardcoded. We need to loop through the args in the commands/insult.js.

**Comment by kyteinsky** [comment]
I have created the feature, but don't know how to test it easily. Will I be needed to create API keys and add the bot to some discord channel to contribute?

**Comment by hitenSharm** [comment]
You can do that, or as the code is most likely pretty small, you can create a pr, I will test it and if it works I will merge it!
