### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#44]
@markvrma has done impressive work on the !obmeme command and the !obgif command, but it's not showcased in the documentation. Take a look at [this](https://github.com/hitenSharm/Discord-Meme-and-Music-Bot/pull/43) for what you need to add in the readme.
Add the new commands with the _proper_ functioning. We don't need to show error handling!
This is only for the readme of the dev branch

**Comment by markvrma** [comment]
I would like to work on this
