### ISSUE TITLE
Can't insult tecno or the bot itself

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#5]
The bot should reply to the author of the message with an insult if someone asks the bot to insult itself or "tecno".
![image](https://user-images.githubusercontent.com/56029311/135571213-6e8e07e9-bda5-4124-8dc6-235935a7390f.png)
Similarly, shouldn't be able to tag "@OkBuddy".
Be sure to care for all sorts of edge cases like "tecnoblade" is ok "tecno" shouldn't work.

**Comment by koushikpuppala** [comment]
Can I work On this

**Comment by markvrma** [comment]
I would like to work on this feature

**Comment by markvrma** [comment]
Could I have the `user id` of @tecno? Since going by `username` could just mean someone renaming themselves on the server to `@tecno`. Also I'm assuming `@okbuddy`  means the bot itself.

**Comment by hitenSharm** [comment]
Make the username an environment variable and test with yours for now.
Yes okbuddy is for the boy itself.

**Comment by markvrma** [comment]
@hitenSharm sir this issue is labeled as medium (20 pts) but on the git-init-foss website i've only been given 10 pts

**Comment by hitenSharm** [comment]
@markvrma you will have to contact the organisers for that. I am not in charge of that stuff.
