### ISSUE TITLE
enhance:MusicBot

### ISSUE THREAD

**Issue by markvrma** [hitenSharm/Discord-Meme-and-Music-Bot#52]
I would like to enhance `!obm play` , such that if it has no arguments it will play a random song from the billboard hot 100 playlist. similar to `!obmeme` or `!insult`.

**Comment by hitenSharm** [comment]
Which api will you use for fetching top 100?

**Comment by markvrma** [comment]
https://www.npmjs.com/package/youtube-playlist , 
https://www.youtube.com/playlist?list=PLDIoUOhQQPlXr63I_vwF9GD8sAKh77dWU ( playlist is regularly updated ),
it could extract the name of a song and pass it into the `discord-music-player` like usual

EDIT : https://npm.runkit.com/billboard-top-100 , directly gets names of songs from the charts based on dates. This is better.
![billboard100](https://user-images.githubusercontent.com/78155861/139577396-65b22e43-fa5f-4267-ac46-74955a8fe728.png)

**Comment by hitenSharm** [comment]
Ok go ahead, give it a try
