### ISSUE TITLE
Repeating insult command 

### ISSUE THREAD

**Issue by hitenSharm** [hitenSharm/Discord-Meme-and-Music-Bot#7]
Currently, if you use the insult command to tag multiple people it will use the same insult twice as the api need some time to generate a new insult.
We need to generate new insults each time. Maybe if we use a feature like setTimeout that will change.
![image](https://user-images.githubusercontent.com/56029311/135622366-62628c7e-a104-492e-bba8-36bb70183343.png)

**Comment by markvrma** [comment]
I would like to work on this.
